=== origin-coding/Alacrity/src/common/PluginSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Plugin schema",
  "description": "Json schema definition for Alacrity plugin.",
  "properties": {
    "Name": {
      "type": "string",
      "description": "Plugin name."
    },
    "Author": {
      "type": "string",
      "description": "Plugin author name."
    },
    "Description": {
      "type": "string",
      "description": "Plugin description."
    },
    "Version": {
      "type": "string",
      "description": "Plugin version."
    },
    "Email": {
      "type": "string",
      "description": "Email address of plugin author."
    },
    "Categories": {
      "type": "array",
      "description": "Plugin category.",
      "items": {
        "enum": [
          "Encrypt",
          "Hash",
          "Format",
          "CheatSheet",
          "CodeSnippet",
          "Generator",
          "Validator",
          "Converter",
          "Parser"
        ]
      },
      "uniqueItems": true
    },
    "MultiLanguage": {
      "type": "boolean",
      "description": "Whether this plugin supports multi-language.",
      "default": false
    },
    "Locale": {
      "type": "object",
      "propertyNames": {
        "enum": ["Name", "Description"]
      },
      "patternProperties": {
        ".*": {
          "type": "object",
          "propertyNames": {
            "enum": ["en", "zhHans"]
          },
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          }
        }
      },
      "required": ["Name", "Description"]
    }
  },
  "if": {
    "properties": {
      "MultiLanguage": {
        "const": true
      }
    },
    "required": ["MultiLanguage"]
  },
  "then": {
    "required": ["Locale"]
  },
  "required": ["Name", "Author", "Description", "Version", "Categories"],
  "additionalProperties": false
}

=== origin-coding/Alacrity/src/AlacrityPlugins/FloatConvert/plugin.json
{
  "Name": "FloatConvert",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A tool for converting single/double precision float numbers.",
  "Categories": ["Converter"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Float Convert",
      "zhHans": "浮点数转换"
    },
    "Description": {
      "en": "Convert float number to binary/hexadecimal form.",
      "zhHans": "将浮点数转换为二进制/十六进制格式。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/UserAgent/plugin.json
{
  "Name": "UserAgent",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A tool for parsing user agent.",
  "Categories": ["Parser"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "User Agent",
      "zhHans": "用户代理解析"
    },
    "Description": {
      "en": "A tool for parsing user agent.",
      "zhHans": "解析用户代理信息。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/Base64/plugin.json
{
  "Name": "Base64",
  "Author": "Alacrity",
  "Description": "A simple base64 encoder/decoder.",
  "Version": "1.0.0",
  "Categories": ["Encrypt"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Base64 Util",
      "zhHans": "Base64工具"
    },
    "Description": {
      "en": "A simple base64 encoder/decoder.",
      "zhHans": "Base64加密/解密工具。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/CssUnit/plugin.json
{
  "Name": "CssUnit",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Css absolute and relative length units.",
  "Categories": ["CheatSheet"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Css Length Units",
      "zhHans": "Css长度单位"
    },
    "Description": {
      "en": "Css absolute and relative length units.",
      "zhHans": "Css绝对和相对长度单位"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/TimeStamp/plugin.json
{
  "Name": "Timestamp",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Convert timestamps.",
  "Categories": ["Converter"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Timestamp Util",
      "zhHans": "时间戳工具"
    },
    "Description": {
      "en": "Convert timestamp to multiple formats.",
      "zhHans": "将时间戳转换为不同的格式。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/UrlParse/plugin.json
{
  "Name": "UrlParse",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A tool for parsing URL.",
  "Categories": ["Parser"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "URL Parse Util",
      "zhHans": "URL解析工具"
    },
    "Description": {
      "en": "Parsing url and viewing its parts.",
      "zhHans": "解析URL，查看URL的各个部分。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/QrCode/plugin.json
{
  "Name": "QrCode",
  "Author": "Alacrity",
  "Description": "A set of QR Code generation tools.",
  "Version": "0.1.0",
  "Categories": ["Generator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "QR Code Generation",
      "zhHans": "二维码生成"
    },
    "Description": {
      "en": "Generate multiple types of QR code and export to image.",
      "zhHans": "生成常用二维码并保存为图片。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/RsaKeyGen/plugin.json
{
  "Name": "RsaKeyGen",
  "Author": "Alacrity",
  "Description": "Generate RSA key pairs.",
  "Version": "1.0.0",
  "Categories": ["Generator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "RSA Keygen",
      "zhHans": "RSA密钥生成"
    },
    "Description": {
      "en": "Generate RSA key pairs.",
      "zhHans": "生成RSA密钥对。"
    }
  }
}
