=== origin-coding/Alacrity/src/common/PluginSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Plugin schema",
  "description": "Json schema definition for Alacrity plugin.",
  "properties": {
    "Name": {
      "type": "string",
      "description": "Plugin name."
    },
    "Author": {
      "type": "string",
      "description": "Plugin author name."
    },
    "Description": {
      "type": "string",
      "description": "Plugin description."
    },
    "Version": {
      "type": "string",
      "description": "Plugin version."
    },
    "Email": {
      "type": "string",
      "description": "Email address of plugin author."
    },
    "Categories": {
      "type": "array",
      "description": "Plugin category.",
      "items": {
        "enum": [
          "Encrypt",
          "Hash",
          "Format",
          "CheatSheet",
          "CodeSnippet",
          "Generator",
          "Validator",
          "Converter",
          "Parser"
        ]
      },
      "uniqueItems": true
    },
    "MultiLanguage": {
      "type": "boolean",
      "description": "Whether this plugin supports multi-language.",
      "default": false
    },
    "Locale": {
      "type": "object",
      "propertyNames": {
        "enum": ["Name", "Description"]
      },
      "patternProperties": {
        ".*": {
          "type": "object",
          "propertyNames": {
            "enum": ["en", "zhHans"]
          },
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          }
        }
      },
      "required": ["Name", "Description"]
    }
  },
  "if": {
    "properties": {
      "MultiLanguage": {
        "const": true
      }
    },
    "required": ["MultiLanguage"]
  },
  "then": {
    "required": ["Locale"]
  },
  "required": ["Name", "Author", "Description", "Version", "Categories"],
  "additionalProperties": false
}

=== origin-coding/Alacrity/src/AlacrityPlugins/CaseConverter/plugin.json
{
  "Name": "CaseConverter",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Converts text to multiple cases",
  "Categories": ["Converter"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Case Converter",
      "zhHans": "大小写转换"
    },
    "Description": {
      "en": "Converts text to multiple cases.",
      "zhHans": "将文本转换为多种大小写格式。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/AddLineNumber/plugin.json
{
  "Name": "AddLineNumber",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Add multiple kinds of line number.",
  "Categories": ["Converter"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Add Line Number",
      "zhHans": "添加行号"
    },
    "Description": {
      "en": "Add multiple kinds of line number.",
      "zhHans": "添加多种格式的行号。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/HashUtils/plugin.json
{
  "Name": "HashUtils",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A tool to hash content and file with multiple algorithms.",
  "Categories": ["Hash"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Hash Utils",
      "zhHans": "哈希工具"
    },
    "Description": {
      "en": "Hash text/binary data with multiple hash algorithms.",
      "zhHans": "使用多种哈希算法对文本数据或二进制数据进行哈希。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/StatusCode/plugin.json
{
  "Name": "StatusCode",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Http response status code cheat sheet.",
  "Categories": ["CheatSheet"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "HTTP Status Code",
      "zhHans": "HTTP响应代码"
    },
    "Description": {
      "en": "Common-used HTTP response status codes.",
      "zhHans": "查看常用HTTP响应代码。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/BaseConvert/plugin.json
{
  "Name": "BaseConvert",
  "Author": "Alacrity",
  "Version": "0.0.0",
  "Description": "A tool for converting number base.",
  "Categories": ["Converter"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Base Convert",
      "zhHans": "进制转换"
    },
    "Description": {
      "en": "A digital base conversion tool.",
      "zhHans": "用于进行数字进制转换的工具。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/RandomNumber/plugin.json
{
  "Name": "RandomNumber",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Generate random numbers.",
  "Categories": ["Generator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Random Generator",
      "zhHans": "随机数生成器"
    },
    "Description": {
      "en": "Generate random numbers.",
      "zhHans": "生成随机数。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/RequestHeaders/plugin.json
{
  "Name": "RequestHeaders",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A tool for getting response headers.",
  "Categories": [],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Request Headers",
      "zhHans": "查看响应头"
    },
    "Description": {
      "en": "View HTTP response headers.",
      "zhHans": "查看HTTP响应头。 "
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/MimeType/plugin.json
{
  "Name": "MimeType",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Common-used MIME types.",
  "Categories": ["CheatSheet"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "MIME Types",
      "zhHans": "常用MIME类型"
    },
    "Description": {
      "en": "Common-used MIME types.",
      "zhHans": "常用MIME类型介绍。 "
    }
  }
}
