=== origin-coding/Alacrity/src/common/PluginSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Plugin schema",
  "description": "Json schema definition for Alacrity plugin.",
  "properties": {
    "Name": {
      "type": "string",
      "description": "Plugin name."
    },
    "Author": {
      "type": "string",
      "description": "Plugin author name."
    },
    "Description": {
      "type": "string",
      "description": "Plugin description."
    },
    "Version": {
      "type": "string",
      "description": "Plugin version."
    },
    "Email": {
      "type": "string",
      "description": "Email address of plugin author."
    },
    "Categories": {
      "type": "array",
      "description": "Plugin category.",
      "items": {
        "enum": [
          "Encrypt",
          "Hash",
          "Format",
          "CheatSheet",
          "CodeSnippet",
          "Generator",
          "Validator",
          "Converter",
          "Parser"
        ]
      },
      "uniqueItems": true
    },
    "MultiLanguage": {
      "type": "boolean",
      "description": "Whether this plugin supports multi-language.",
      "default": false
    },
    "Locale": {
      "type": "object",
      "propertyNames": {
        "enum": ["Name", "Description"]
      },
      "patternProperties": {
        ".*": {
          "type": "object",
          "propertyNames": {
            "enum": ["en", "zhHans"]
          },
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          }
        }
      },
      "required": ["Name", "Description"]
    }
  },
  "if": {
    "properties": {
      "MultiLanguage": {
        "const": true
      }
    },
    "required": ["MultiLanguage"]
  },
  "then": {
    "required": ["Locale"]
  },
  "required": ["Name", "Author", "Description", "Version", "Categories"],
  "additionalProperties": false
}

=== origin-coding/Alacrity/src/AlacrityPlugins/Ascii/plugin.json
{
  "Name": "Ascii",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Information of ASCII codes.",
  "Categories": ["CheatSheet"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "ASCII Codes Info",
      "zhHans": "ASCII码信息汇总"
    },
    "Description": {
      "en": "List all ASCII codes' information.",
      "zhHans": "列出ASCII码的常用信息。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/MacGenerator/plugin.json
{
  "Name": "MacGenerator",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Generate random Mac addresses.",
  "Categories": ["Generator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Mac Generator",
      "zhHans": "随机Mac地址生成"
    },
    "Description": {
      "en": "Generate random Mac addresses.",
      "zhHans": "生成随机的Mac地址。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/Uuid/plugin.json
{
  "Name": "Uuid",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A simple tool for UUID generation/validation.",
  "Categories": ["Generator", "Validator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "UUID Utils",
      "zhHans": "UUID工具"
    },
    "Description": {
      "en": "Generating and validating random UUIDs.",
      "zhHans": "随机生成和验证UUID。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/IpGenerator/plugin.json
{
  "Name": "IpGenerator",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "Generate Ip v4/v6 addresses.",
  "Categories": ["Generator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Ip Generator",
      "zhHans": "Ip地址生成"
    },
    "Description": {
      "en": "Generate Ip v4/v6 addresses.",
      "zhHans": "生成Ip v4/v6地址。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/IpCalculator/plugin.json
{
  "Name": "IpCalculator",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A simple IP address calculator.",
  "Categories": [],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "IP Calculator",
      "zhHans": "IP地址计算器"
    },
    "Description": {
      "en": "Calculate available ip addresses.",
      "zhHans": "计算可用IP地址。"
    }
  }
}

=== origin-coding/Alacrity/src/AlacrityPlugins/Faker/plugin.json
{
  "Name": "Faker",
  "Author": "Alacrity",
  "Version": "1.0.0",
  "Description": "A tool for generating fake data.",
  "Categories": ["Generator"],
  "MultiLanguage": true,
  "Locale": {
    "Name": {
      "en": "Faker",
      "zhHans": "Faker工具"
    },
    "Description": {
      "en": "Generate fake data in CSV form.",
      "zhHans": "以CSV格式生成模拟数据。"
    }
  }
}
